### ISSUE TITLE
Can't write anymore after approx 18 hours

### ISSUE THREAD

**Issue by cskaandorp** [mugimaru/webdavex#2]
Hi, 

First of all: I am a user, not hindered by any fundamental knowlegde about Webdav, I just want to put files on a remote filesystem. So I hope I didn't oversee something stupid here.

I have created a Phoenix app that sends csv files to a remote filesystem every 15 mins, 24/7. I am using a genserver to accomplish this. Once the system wants to dump its data, I fire up a Client and do the deed with the put function. That goes well until approx 18 hours. After that I get a :checkout_timeout, and that remains until I restart the application. No data will be transferred although the app keeps trying.

My first step was to contact the admin of the remote filesystem. All seems in order on that side. And it is weird that everything runs fine (and note I create a single Client every time I want to send a file) for a long time.

My question: starting a client is done with Webdavex.Config.new according to the examples. I was wondering if the connection between my app and the remote server remains open(?). Maybe I am having too many connections open and it's causing this problem. If it is plausible: how do I stop this?

I fully realize that my lack of knowledge is probably the main issue here. But maybe you can shed some light on this.

Thanks in advance, 

Casper

**Comment by mugimaru** [comment]
Hey Casper, sorry for the late response. 
0.3.1 fixes PUT connections leaking. See [this commit](https://github.com/mugimaru/webdavex/commit/b3a9092e8759c0cc825d6bcbabc3412a6e224098) for details.

**Comment by cskaandorp** [comment]
Hi mugimaru, 

Thanks for the fix. I was in a pickle and in the end I had to take a step down and use HTTPoison to get the app going. But it is good to know that it has been fixed. Merry x-mas!

Cspr
